-- Database + tables to test
DROP DATABASE IF EXISTS PLD;
CREATE DATABASE IF NOT EXISTS PLD;
USE PLD;

CREATE TABLE IF NOT EXISTS states ( 
    id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);
